wandb_version: 1

out_dir:
  desc: null
  value: out_last_char_token_to_token
eval_interval:
  desc: null
  value: 200
log_interval:
  desc: null
  value: 1
eval_iters:
  desc: null
  value: 200
eval_only:
  desc: null
  value: false
always_save_checkpoint:
  desc: null
  value: true
init_from:
  desc: null
  value: scratch
wandb_log:
  desc: null
  value: true
wandb_project:
  desc: null
  value: owt
wandb_run_name:
  desc: null
  value: gpt2_last_char_token_to_char1729664747.264537
dataset:
  desc: null
  value: openwebtext_last_char_token_to_char
gradient_accumulation_steps:
  desc: null
  value: 40
batch_size:
  desc: null
  value: 12
block_size:
  desc: null
  value: 256
n_layer:
  desc: null
  value: 12
n_head:
  desc: null
  value: 12
n_embd:
  desc: null
  value: 768
dropout:
  desc: null
  value: 0.0
bias:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.0006
max_iters:
  desc: null
  value: 600000
weight_decay:
  desc: null
  value: 0.1
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.95
grad_clip:
  desc: null
  value: 1.0
decay_lr:
  desc: null
  value: true
warmup_iters:
  desc: null
  value: 2000
lr_decay_iters:
  desc: null
  value: 600000
min_lr:
  desc: null
  value: 6.0e-05
gated_K:
  desc: null
  value: false
difference:
  desc: null
  value: false
gated_attention:
  desc: null
  value: false
backend:
  desc: null
  value: nccl
device:
  desc: null
  value: mps
dtype:
  desc: null
  value: float16
compile:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    code_path: code/train_last_char_token_to_char.py
    python_version: 3.10.0
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.45.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1729664752.255808
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 105
      2:
      - 1
      - 11
      - 49
      - 55
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.10.0
      5: 0.15.8
      6: 4.45.1
      8:
      - 4
      - 5
